### ISSUE TITLE
Dots invisible depending on terminal type

### ISSUE THREAD

**Issue by jugglerchris** [NerdyPepper/dijo#50] opened 2020-07-24 20:48 UTC
Thanks for this tool which I think will be very useful!

When I updated to 0.2.2 I found the dots in the month layout aren't visible; I believe they're black on black on my terminal (I can copy them to another terminal and they come out ok).

So far I've found:
* It happens on 0.2.2 but not 0.2.1
* It depends on the value of `TERM`.  I'm running in a gnome-terminal (with or without tmux) on Ubuntu 19.10, and it works with the `TERM` environment variable set to `xterm-256color` but not with any of `xterm`, `xterm-color`, or `screen`.

I'm guessing it's the recent change to use pancurses; I tried building a couple of commits before that but had build errors (missing termion); I could build commit 2f47f50 which didn't have the issue.

**Comment by NerdyPepper** [comment] 2020-07-29 04:06
Yep, seems to be caused by the switch to `pancurses`, works fine with `xterm-256-color` as you said. I will probably switch back to termion for *nix and use crossterm for windows with a feature flag. 

It might be worth opening an issue over at the [pancurses](https://github.com/ihalila/pancurses) repo.

**Comment by NerdyPepper** [comment] 2020-08-04 08:01
Should be fixed as of v0.2.3, feel free to reopen otherwise.

**Closed by NerdyPepper** 2020-08-04 08:01 UTC
